### ISSUE TITLE
ἔστι fails to syllabify properly

### ISSUE THREAD

**Issue by neelsmith** [neelsmith/gsphonology#6]
Running the following code in sbt, in which urn:cts:greekMusic:seikilos.1.normalized: contains the word ἔστι:

val seikilosTextUrn = CtsUrn("urn:cts:greekMusic:seikilos.1.normalized:")
val seikilosTextCorpus = repo.corpus ~~ seikilosTextUrn
val diplomaticText = reader.edition(seikilosTextCorpus)
val seikilosWordsCorpus = LiteraryGreekString.tokenizedCorpus(diplomaticText)
val seikilosTextSyllableCorpus = LGSyllable.tokenizedCorpus(seikilosWordsCorpus)
val seikilosTextSyllables = seikilosTextSyllableCorpus.nodes
seikilosTextSyllables(16)

Garners this result:

res9: edu.holycross.shot.ohco2.CitableNode = CitableNode(urn:cts:greekMusic:seikilos.1.normalized_dipl_tkns_sylls:3.2.0,ἔστι)

ἔστι here does not seem to be syllabifying properly. Interestingly enough ἐστὶ syllabifies fine

**Comment by zachsowerby** [comment]
αἴγλας also does not syllabify.

**Comment by zachsowerby** [comment]
μόσχων

**Comment by neelsmith** [comment]
Tested, fixed.
